server:
  port: 8181

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: service-usuario
          uri: http://localhost:8081
          predicates:
            - Path=/api/v2/usuarios/**, /api/v1/bandas/**

        - id: service-rig-equipos
          uri: http://localhost:8085
          predicates:
            - Path=/api/v2/equipos/en-cancion/**

        - id: service-inventario
          uri: http://localhost:8082
          predicates:
            - Path=/api/v2/equipos/**, /api/v2/marcas/**, /api/v2/categorias/**

        - id: service-specs
          uri: http://localhost:8083
          predicates:
            - Path=/api/v2/especs/**

        - id: service-mantenimiento
          uri: http://localhost:8084
          predicates:
            - Path=/api/v2/mantenimientos/**

        - id: service-rig
          uri: http://localhost:8085
          predicates:
            - Path=/api/v2/canciones/**

        - id: service-evento
          uri: http://localhost:8086
          predicates:
            - Path=/api/v2/eventos/**