server:
  port: 8181

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:9090"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
      routes:
        - id: service-usuario
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/usuarios/**, /api/v1/bandas/**

        - id: service-rig-equipos
          uri: http://localhost:8085
          predicates:
            - Path=/api/v1/equipos/en-cancion/**

        - id: service-inventario
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/equipos/**, /api/v1/marcas/**, /api/v1/categorias/**

        - id: service-specs
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/especs/**

        - id: service-mantenimiento
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/mantenimientos/**

        - id: service-rig
          uri: http://localhost:8085 
          predicates:
            - Path=/api/v1/canciones/**

        # --- Nuevos Microservicio ---
        - id: service-logistica
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/logistica/**

        - id: logistica-docs
          uri: http://localhost:8090
          predicates:
            - Path=/logistica/api-docs

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

springdoc:
  swagger-ui:
    urls:
      - name: Servicio Logistica
        url: /logistica/api-docs

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG